//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.TicketComments = new HashSet<TicketComment>();
        }
    
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int OwnerId { get; set; }
        public int TypeId { get; set; }
        public int PriorityId { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> AssigneeId { get; set; }
        public string Description { get; set; }
        public System.DateTimeOffset CreationTime { get; set; }
        public System.DateTimeOffset UpdatedTime { get; set; }
        public string Title { get; set; }
    
        public virtual TicketPriority TicketPriority { get; set; }
        public virtual TicketStatus TicketStatus { get; set; }
        public virtual TicketType TicketType { get; set; }
        public virtual UserModel Owner { get; set; }
        public virtual UserModel Assignee { get; set; }
        public virtual ICollection<TicketComment> TicketComments { get; set; }
        public virtual Project Project { get; set; }
    }
}
