//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketComment
    {
        public int Id { get; set; }
        public int TicketId { get; set; }
        public int PosterId { get; set; }
        public string Message { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual UserModel Poster { get; set; }
    }
}
