//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackerDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserModel
    {
        public UserModel()
        {
            this.SubmittedTickets = new HashSet<Ticket>();
            this.AssignedTickets = new HashSet<Ticket>();
            this.TicketComments = new HashSet<TicketComment>();
            this.UserProjectRoles = new HashSet<UserProjectRole>();
            this.TicketAttachments = new HashSet<TicketAttachment>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool Admin { get; set; }
    
        public virtual ICollection<Ticket> SubmittedTickets { get; set; }
        public virtual ICollection<Ticket> AssignedTickets { get; set; }
        public virtual ICollection<TicketComment> TicketComments { get; set; }
        public virtual ICollection<UserProjectRole> UserProjectRoles { get; set; }
        public virtual ICollection<TicketAttachment> TicketAttachments { get; set; }
    }
}
